### ISSUE TITLE
Internal server error: Codegen node is missing for element/if/for node. Apply appropriate transforms first.

### ISSUE THREAD

**Issue by plc-dev** [qmhc/grid-layout-plus#8]
Thanks for porting grid-layout to vue 3.

Sadly, I receive the following error when trying any of the examples:

```[vite] Internal server error: Codegen node is missing for element/if/for node. Apply appropriate transforms first.
  Plugin: vite:vue
  File: E:/ALADIN_Orga/_workspace/CARPET/src/views/ComponentTest.vue
      at assert (E:\ALADIN_Orga\_workspace\CARPET\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:496:11)
      at genNode (E:\ALADIN_Orga\_workspace\CARPET\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2474:7)
      at genNodeList (E:\ALADIN_Orga\_workspace\CARPET\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2449:7)
      at genNodeListAsArray (E:\ALADIN_Orga\_workspace\CARPET\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2436:3)
      at genNodeList (E:\ALADIN_Orga\_workspace\CARPET\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2447:7)
      at genVNodeCall (E:\ALADIN_Orga\_workspace\CARPET\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2616:3)
      at genNode (E:\ALADIN_Orga\_workspace\CARPET\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2499:7)
      at genNode (E:\ALADIN_Orga\_workspace\CARPET\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2478:7)
      at genNodeList (E:\ALADIN_Orga\_workspace\CARPET\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2449:7)
      at genNodeListAsArray (E:\ALADIN_Orga\_workspace\CARPET\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2436:3)
```

When cloning the repository and installing locally, the devserver is working though. 
I've seen [this](https://stackoverflow.com/questions/74028448/vite-internal-server-error-codegen-node-is-missing-for-element-if-for-node-app) and [this](https://vuejs.org/guide/components/slots.html#scoped-slots), but have not managed to get it up and running.

The [vue documentation](https://vuejs.org/guide/components/slots.html#scoped-slots) states it might be related to default slots, that are used in combination with named slots, but I've not come up with a way to solve this yet.

Any idea on what causes the issue?

**Comment by plc-dev** [comment]
Figured it out. 100% user-error. Due to some issues with the original version of Grid-Layout from [jbaysolutions](https://github.com/jbaysolutions/vue-grid-layout), I had defined a custom template for the GridLayout-component in the vite-configuration:

```typescript
import { fileURLToPath, URL } from "node:url";

import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({
      template: {
        compilerOptions: {
          isCustomElement: (tag) => ["GridLayout"].includes(tag)
        }
      }
    })
  ],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url))
    }
  },
  server: {
    proxy: {
      "/api": {
        target: "http://localhost:8000",
        changeOrigin: true
      }
    }
  }
});
```

Removing the custom template and simply passing an empty object to the vue-instance alleviates the issue.

Thanks for the nice work on the port!
